# Generated by Django 3.2.1 on 2021-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='taked_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='Взято заданий'),
        ),
        migrations.AddField(
            model_name='profile',
            name='worker_type',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Должность'),
        ),
    ]
