# Generated by Django 3.2.1 on 2021-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_profile_utask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='taked_tasks_qty',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Взято заданий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='worker_type',
            field=models.CharField(blank=True, default='NULL', max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
