# Generated by Django 3.2.1 on 2021-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20210805_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='utask',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
