# Generated by Django 3.2.1 on 2021-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_utask_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='utask',
            name='u_task',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
    ]
