# Generated by Django 3.2.1 on 2021-08-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20210803_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача пользователей', 'verbose_name_plural': 'Задачи пользователей'},
        ),
    ]
