# Generated by Django 3.2.1 on 2021-08-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='utask',
            options={'verbose_name': 'Задача пользователей', 'verbose_name_plural': 'Задачи пользователей'},
        ),
        migrations.RenameField(
            model_name='utask',
            old_name='task',
            new_name='usr_task',
        ),
        migrations.RenameField(
            model_name='utask',
            old_name='title',
            new_name='usr_title',
        ),
    ]
