# Generated by Django 3.2.1 on 2021-09-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_alter_worker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='u_individual_task',
        ),
    ]
