# Generated by Django 3.2.1 on 2021-09-19 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_remove_profile_u_individual_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='taked_tasks_qty',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='worker_type',
        ),
        migrations.AddField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='worker',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='worker',
            name='birthday_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='worker',
            name='education',
            field=models.CharField(choices=[('Среднее общее', 'Среднее общее'), ('Высшее', 'Высшее'), ('Неоконченное высшее', 'Неоконченное высшее')], default='Неоконченное высшее', max_length=160, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='worker',
            name='foreign_languages',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Иностранные языки'),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(blank=True, default='NULL', max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
